### ISSUE TITLE
Catching Readtimeout exception and related errors.

### ISSUE THREAD

**Issue by DurgNomis-drol** [DurgNomis-drol/mytoyota#148]
**Describe the bug**
In my HA integration I need to do below to catch some exceptions thrown by Toyota's servers because it is to slow to respond when processing a request.

```python
 except (
            asyncioexceptions.CancelledError,
            asyncioexceptions.TimeoutError,
            httpx.ReadTimeout,
        ) as ex:

            raise UpdateFailed(
                "Update canceled! Toyota's API was too slow to respond."
                " Will try again later..."
            ) from ex

```

**To Reproduce**

**Expected behavior**

I would love to move this to here instead, but I am unsure of what the best way to do it, and maybe even handle the error silently by doing the request again or something. What do you think @joro75 ?

**Additional context**

**Comment by joro75** [comment]
A possible solution is to retry and perform the operation again. So we for example perform the request up to 3 times. If we then at the third time still have the timeout- or or cancelled-exception we still have to re-raise the exception.
So you will never be able to remove the exception handling from your HA integration. Another possibility is of course that due to the not-performed request after 3 tries a 'None' is being returned by the called function.

**Comment by CM000n** [comment]
We have recently released a beta version for the new API endpoints and will be focussing our work on this in the future.
Please check if your issue still applies to the new version.

**Comment by CM000n** [comment]
The new API is much more responsive. I haven't noticed any more timeouts of this kind while working on the Home Assistant component.
I therefore think that we can close the ticket and should create a new one if there is a real need.
