### ISSUE TITLE
Implement typing

### ISSUE THREAD

**Issue by DurgNomis-drol** [DurgNomis-drol/mytoyota#2]
Type check everything. Though not aiming for enabling strict typing yet.

**Comment by joro75** [comment]
Hi Simon,

I'm willing to help you with adding more typing to the mytoyota library. With the final goal to resolve all mypy warnings and errors. 
I already checked the current status, and I observed that already almost all functions and members are using type annotations, but several of them are not yet correct.

This is however raising some questions which I would like to discuss, before I implement a lot of chances. Let's for example take:
```python
class Odometer:
    """Odometer representation"""

    mileage: int = None
    unit: str = None

    def __init__(self, data: dict) -> None:
        self.mileage = data.get("mileage", None)
        self.unit = data.get("mileage_unit", None)
```
I do have several suggestions:
1) `mileage` and `unit` are initially defined as being class members. Wouldn't it be more logical to only define them as instance members? Please see: https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables 
Having `mileage` and `unit` shared between multiple instances of `Odometer` is in my opinion not desired.
2) To correctly type `mileage`, also being able to assign `None` to it, the type annotation should be: `Optional[int]`. This is of course possible, however it does require that a lot of the other code should include checks to determine if the value is `None`. Wouldn't it be better, if the classes only contain the member if it is defined? The `getattr` or `hasattr` can then be used to retrieve the value instead of a lot of `None` checks.
This will also help to resolve the fluctuating nature of the Toyota API, where components are sometimes are present and sometimes are not present. Class members are then just not present if the information is not provided by the Toyota API.

Based on this I would like to suggest to change the above example to:
```python
class Odometer:
    """Odometer representation"""

    def __init__(self, data: dict) -> None:
        if "mileage" in data:
            self.mileage: int = data.get("mileage")
        self.unit: str = data.get("mileage_unit", "km")
```

I do realize that this will introduce some large changes in the code, but as I wrote: I'm willing to do this for you. At the same time, I also think it is possible to add Python tests to the library (#1)

**Comment by DurgNomis-drol** [comment]
I would love this!! You are right in all the of the above points. The code could be a LOT better, but i am still learning. So having you help would be awesome. 

I have been thinking about using `hasattr` and `getattr` lately, but because of my skill level, the task have been a bit overwhelming.

For example: Toyota returns HVAC information from to different endpoints depending on the car model, which is quiet a pain. The same for battery/charge information and fuel level. 🤦 So a lot of things became a patch job to make it work. But it gets harder and harder without tests (Need to learn to implement them as well). Any help i can get maintaining this is appreciated a lot. 

Just send those PR's and i will review them (and probably ask a lot of questions so i can learn, hope that is okay) 😄 

I am not that good of a programmer, learned python at the start of the year, so still trying to understand the best ways to build a module, and this is also reflected in how much the codebase have changed the last 6 months. 😄 My day job is as an electrician.

**Comment by joro75** [comment]
Ok. Clear. 

You should be proud on the Python code you wrote. It is not that bad at all!! I have seen much much worse pieces of code.

Thanks for agreeing on my suggestions. I will send in the PR's, however it will probably be multiple separate PR's, because changing it all at once is just a too high risk of breaking things. Also for that reason I will start with adding unittests so we can ensure that the code remains functional during the upcoming changes.

**Comment by CM000n** [comment]
I think this can bei closed @DurgNomis-drol & @joro75.
Thanks to your great preparatory work, we use type hints in all relevant places. 😊
