### ISSUE TITLE
how to get information for a single vehicle?

### ISSUE THREAD

**Issue by noyax** [DurgNomis-drol/mytoyota#329]
### Discussed in https://github.com/DurgNomis-drol/mytoyota/discussions/328

<div type='discussions-op-text'>

<sup>Originally posted by **noyax** February  6, 2024</sup>
Hello, I have two vehicles associated with my mytoyota account and I would like to have the information only for one vehicle, is this possible and if so how should I do it?

thanks in advance</div>

**Comment by CM000n** [comment]
The `simple_client_example.py` example is, as the name suggests, only an example, and not the mytoyota python lib itself 😉 
So you can use it as you like. 😊 

Obtaining data for a specific vehicle always requires knowing the VIN of that vehicle. Since we assume that the majority of users do not know the VIN of their vehicle, the query of data for a specific Vin is not integrated as a callable parameter. We therefore automatically determine all vehicles for a user first.
